"""Synthetic customer-persona fixtures for the advice domain (bossyk-sandbox
privacy/minimisation demonstrator, Phase 1). Entirely fictional records,
generated by seeded code so the fixture is deterministic and reviewable --
no real data, no third-party dataset (see the plan's "Persona data"
decision).
"""

from __future__ import annotations

import random
from dataclasses import dataclass

# Deliberately NOT real UK postcode allocations -- the "ZZ" outward-code
# prefix is unused by Royal Mail, keeping every generated postcode obviously
# synthetic at a glance.
_POSTCODE_AREAS = ["ZZ1", "ZZ2", "ZZ3", "ZZ4", "ZZ5"]
_POSTCODE_LETTERS = "ABDEFGHJLNPQRSTUWXYZ"

_FIRST_NAMES = [
    "Alex",
    "Priya",
    "Jordan",
    "Sam",
    "Morgan",
    "Chris",
    "Taylor",
    "Leah",
    "Ravi",
    "Emma",
    "Noah",
    "Aisha",
]
_LAST_NAMES = [
    "Fenwick",
    "Okonkwo",
    "Bramley",
    "Castellan",
    "Dunmore",
    "Ellery",
    "Farrant",
    "Gough",
    "Haslam",
    "Iyer",
    "Jephcott",
    "Kilbride",
]

DEFAULT_SEED = 20260804
DEFAULT_COUNT = 8

# Income buckets cycled by persona index so the committed fixture set
# deterministically spans all three UK income-tax bands
# (bossyk_sandbox.advice.tax) rather than leaving band coverage to chance.
_INCOME_BUCKETS_GBP = [
    (18_000, 48_000),  # basic
    (55_000, 115_000),  # higher
    (130_000, 190_000),  # additional
]


@dataclass(frozen=True)
class PersonaRecord:
    """One fictional advice-domain customer. `health_condition_flag` is the
    demonstrator's single special-category (UK GDPR Art. 9) field."""

    ref: str
    full_name: str
    date_of_birth: str  # ISO 8601 date, e.g. "1978-04-12"
    postcode: str
    annual_income_gbp: int
    health_condition_flag: bool


def _random_postcode(rng: random.Random) -> str:
    area = rng.choice(_POSTCODE_AREAS)
    district = rng.randint(1, 9)
    inward = f"{rng.randint(0, 9)}{rng.choice(_POSTCODE_LETTERS)}{rng.choice(_POSTCODE_LETTERS)}"
    return f"{area}{district} {inward}"


def _random_date_of_birth(rng: random.Random) -> str:
    year = rng.randint(1955, 2003)
    month = rng.randint(1, 12)
    day = rng.randint(1, 28)  # avoids month-length edge cases; fictional data only
    return f"{year:04d}-{month:02d}-{day:02d}"


def generate_personas(
    seed: int = DEFAULT_SEED, count: int = DEFAULT_COUNT
) -> list[PersonaRecord]:
    """Deterministically generates `count` fictional customer personas from
    `seed`. Same seed -> byte-identical output, which is what makes the
    committed `PERSONAS` fixture below reproducible without being
    hand-typed data."""
    rng = random.Random(seed)
    records = []
    for i in range(count):
        low, high = _INCOME_BUCKETS_GBP[i % len(_INCOME_BUCKETS_GBP)]
        records.append(
            PersonaRecord(
                ref=f"ADV-{i + 1:04d}",
                full_name=f"{rng.choice(_FIRST_NAMES)} {rng.choice(_LAST_NAMES)}",
                date_of_birth=_random_date_of_birth(rng),
                postcode=_random_postcode(rng),
                annual_income_gbp=rng.randint(low, high),
                health_condition_flag=rng.random() < 0.25,
            )
        )
    return records


PERSONAS: list[PersonaRecord] = generate_personas()


@dataclass
class PersonaStore:
    """Read-only lookup over a persona list, keyed by `ref`. Both the raw
    and derived tool surfaces (`advice.toolkit.AdviceToolkit`) read through
    the SAME store instance -- there is exactly one source of truth per
    session, never a separate raw vs. derived copy of the data."""

    records: list[PersonaRecord]

    def __post_init__(self) -> None:
        index: dict[str, PersonaRecord] = {}
        for record in self.records:
            if record.ref in index:
                raise ValueError(f"duplicate persona ref: {record.ref!r}")
            index[record.ref] = record
        self._index = index

    def get(self, ref: str) -> PersonaRecord:
        try:
            return self._index[ref]
        except KeyError:
            raise KeyError(f"unknown persona ref: {ref!r}") from None

    def refs(self) -> list[str]:
        return [record.ref for record in self.records]
