"""RED-phase tests for the interrupt-before-EMIT utterance hook
(bossyk-sandbox slice 2, P6; scope-doc D4).

A speech act can't be "not executed" -- it has already been generated by the
time `agent_node` sees it. The enforcement primitive is suppression/
replacement BEFORE the response message is appended to graph state. This
file tests the MECHANISM with a synthetic always-block/always-allow fake
`UtteranceInstrument` (per the coordinator's ask: "assert the mechanism ...
not a live model") -- `ProhibitedPhraseRule` itself is covered separately in
test_prohibited_phrase_rule.py.

Target: a new `utterance_rules: list[UtteranceInstrument]` keyword param on
`_build_agent_session`, defaulting to `[]`. Tested directly against
`_build_agent_session` (private, but the repo already tests private helpers
directly elsewhere, e.g. `_resolve_agent_config` in test_langgraph_agent.py)
since the public wrappers (`build_airline_agent_session` etc.) do not yet
expose it and P6 does not ask for that per-domain wiring.

FLAG for the RED gate (not decided here): how a suppressed utterance is
represented downstream. These tests assert only the externally-observable
mechanism -- the final message's content changes and no longer contains the
regulated text -- not a specific trace/Step/Decision shape, since that
wiring (a new Decision path vs. a replacement message vs. a Step annotation)
is a GREEN decision.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

import pytest
from langchain_core.messages import AIMessage, HumanMessage

from bossyk_sandbox.instruments.base import Decision, ProposedAction, Verdict


@dataclass
class _ScriptedLLM:
    responses: list[AIMessage]
    calls: int = 0

    def invoke(self, _messages: Any) -> AIMessage:
        response = self.responses[self.calls]
        self.calls += 1
        return response


@dataclass
class _CountingToolkit:
    counts: dict[tuple[str, tuple[tuple[str, Any], ...]], int] = field(default_factory=dict)

    def get_tools(self) -> dict[str, Any]:
        return {}

    def use_tool(self, name: str, **kwargs: Any) -> str:
        key = (name, tuple(sorted(kwargs.items())))
        self.counts[key] = self.counts.get(key, 0) + 1
        return "ok"


@dataclass
class _FakeEnvironment:
    tools: _CountingToolkit
    policy: str = "test policy"


@dataclass
class _AlwaysBlockUtterance:
    """Synthetic UtteranceInstrument: blocks every utterance, unconditionally
    -- isolates the WIRING (does agent_node consult utterance_rules at all,
    before appending the message?) from the phrase-matching logic itself."""

    reason: str = "test: always blocks"

    def score(self, text: str, history: Any) -> Decision:
        return Decision(Verdict.BLOCK, self.reason)


@dataclass
class _AlwaysAllowUtterance:
    def score(self, text: str, history: Any) -> Decision:
        return Decision(Verdict.ALLOW, "test: always allows")


def _no_env() -> Any:
    raise AssertionError("get_environment_fn must not be called when environment= is injected")


def _invoke_once(session: Any, *, thread_id: str) -> dict[str, Any]:
    config = {"configurable": {"thread_id": thread_id}}
    result: dict[str, Any] = session.graph.invoke(
        {"messages": [HumanMessage(content="tell me about your finance options")]}, config=config
    )
    return result


def test_build_agent_session_accepts_an_utterance_rules_param() -> None:
    from bossyk_sandbox.runtime.langgraph_agent import _build_agent_session

    llm = _ScriptedLLM(responses=[AIMessage(content="We can offer 0% finance on this order.")])
    toolkit = _CountingToolkit()

    # Must not raise TypeError for an unexpected keyword argument.
    session = _build_agent_session(
        trace_id="t-utterance-param",
        get_environment_fn=_no_env,
        fast_rules=[],
        model_name=None,
        api_key=None,
        base_url=None,
        llm=llm,
        environment=_FakeEnvironment(tools=toolkit),
        utterance_rules=[],
    )

    assert session is not None


def test_agent_node_suppresses_a_prohibited_utterance_before_it_is_emitted() -> None:
    from bossyk_sandbox.runtime.langgraph_agent import _build_agent_session

    original_text = "We can offer 0% finance on this order."
    llm = _ScriptedLLM(responses=[AIMessage(content=original_text)])
    toolkit = _CountingToolkit()

    session = _build_agent_session(
        trace_id="t-utterance-block",
        get_environment_fn=_no_env,
        fast_rules=[],
        model_name=None,
        api_key=None,
        base_url=None,
        llm=llm,
        environment=_FakeEnvironment(tools=toolkit),
        utterance_rules=[_AlwaysBlockUtterance()],
    )

    result = _invoke_once(session, thread_id="utterance-block")

    last_message = result["messages"][-1]
    assert original_text not in last_message.content
    assert "__interrupt__" not in result  # no tool call was ever proposed


def test_agent_node_allows_a_clean_utterance_through_unchanged() -> None:
    from bossyk_sandbox.runtime.langgraph_agent import _build_agent_session

    original_text = "I'll book your free survey now, no charge."
    llm = _ScriptedLLM(responses=[AIMessage(content=original_text)])
    toolkit = _CountingToolkit()

    session = _build_agent_session(
        trace_id="t-utterance-allow",
        get_environment_fn=_no_env,
        fast_rules=[],
        model_name=None,
        api_key=None,
        base_url=None,
        llm=llm,
        environment=_FakeEnvironment(tools=toolkit),
        utterance_rules=[_AlwaysAllowUtterance()],
    )

    result = _invoke_once(session, thread_id="utterance-allow")

    last_message = result["messages"][-1]
    assert last_message.content == original_text


# --- BYTE-IDENTICAL: utterance_rules defaults to [] ------------------------


def test_agent_node_is_byte_identical_when_utterance_rules_is_omitted() -> None:
    # Even a clearly "regulated" utterance passes through UNCHANGED when no
    # utterance_rules are configured (airline/retail/outreach's actual
    # behaviour today -- none of them pass utterance_rules).
    from bossyk_sandbox.runtime.langgraph_agent import _build_agent_session

    original_text = "We can offer 0% finance on this order."
    llm = _ScriptedLLM(responses=[AIMessage(content=original_text)])
    toolkit = _CountingToolkit()

    session = _build_agent_session(
        trace_id="t-utterance-default",
        get_environment_fn=_no_env,
        fast_rules=[],
        model_name=None,
        api_key=None,
        base_url=None,
        llm=llm,
        environment=_FakeEnvironment(tools=toolkit),
    )

    result = _invoke_once(session, thread_id="utterance-default")

    last_message = result["messages"][-1]
    assert last_message.content == original_text


def test_agent_node_is_byte_identical_with_an_explicit_empty_utterance_rules_list() -> None:
    from bossyk_sandbox.runtime.langgraph_agent import _build_agent_session

    original_text = "We can offer 0% finance on this order."
    llm = _ScriptedLLM(responses=[AIMessage(content=original_text)])
    toolkit = _CountingToolkit()

    session = _build_agent_session(
        trace_id="t-utterance-empty-list",
        get_environment_fn=_no_env,
        fast_rules=[],
        model_name=None,
        api_key=None,
        base_url=None,
        llm=llm,
        environment=_FakeEnvironment(tools=toolkit),
        utterance_rules=[],
    )

    result = _invoke_once(session, thread_id="utterance-empty-list")

    last_message = result["messages"][-1]
    assert last_message.content == original_text


def test_build_airline_agent_session_is_unaffected_by_the_new_param_existing() -> None:
    # Sanity: the public wrapper's call site (no utterance_rules threaded
    # through it yet -- a GREEN/follow-on question, not decided here) must
    # still build a working session with the default fast_rules.
    from bossyk_sandbox.runtime.langgraph_agent import build_airline_agent_session

    llm = _ScriptedLLM(responses=[AIMessage(content="done")])
    toolkit = _CountingToolkit()

    session = build_airline_agent_session(
        trace_id="t-airline-unaffected", llm=llm, environment=_FakeEnvironment(tools=toolkit)
    )

    assert session.gate is not None


@pytest.mark.parametrize("history", [[], [ProposedAction("get_thing", {})]])
def test_always_block_fake_ignores_history_shape(history: Any) -> None:
    # Sanity check on the fake itself: it must accept whatever history shape
    # agent_node passes (this repo's convention: don't over-fit a fake to
    # one call site).
    rule = _AlwaysBlockUtterance()

    decision = rule.score("anything", history)

    assert decision.verdict is Verdict.BLOCK
